### PR TITLE
Filenames can now be variable length. Should fix issue #109.

### PR DESCRIPTION
**Pull request by atillack**
Please test in multithreaded, pipeline, and regular modes to make sure affected code paths are working properly :-)

### CODE REVIEW

**Comment by L30nardoSV** [comment]
Thanks for the fixes @atillack. 

I've tested commit `396556a` with simple commands, without _yet_ using long paths, just as a preliminary test. The .dlg file is produced, but core is dumped:

* `make DEVICE=GPU test` and  `make DEVICE=OCLGPU test` produce similar outputs:

```bash
[...]
./bin/autodock_gpu_64wi \
-ffile ./input/3ce3/derived/3ce3_protein.maps.fld \
-lfile ./input/3ce3/derived/3ce3_ligand.pdbqt \
-nrun 100 \
-ngen 27000 \
-psize 150 \
-resnam test \
-gfpop 0 \
-lsmet sw
AutoDock-GPU version: v1.3-2-g396556a773c2a1c153232228f35baaeedddb2dbb

Kernel source used for development:      ./device/calcenergy.cl                  
Kernel string used for building:         ./host/inc/stringify.h                  
Kernel compilation flags:                 -I ./device -I ./common -DN64WI   -cl-mad-enable
OpenCL device:                           GeForce RTX 2070 SUPER
(Thread 0 is setting up Job 0)

Running Job #0:
Local-search chosen method is: Solis-Wets (sw)

Executing docking runs:
        20%        40%       60%       80%       100%
---------+---------+---------+---------+---------+
**************************************************

Job #0 took 9.211 sec after waiting 0.356 sec for setup

(Thread 0 is processing Job 0)

Run time of entire job set (1 file): 9.896 sec
corrupted size vs. prev_size in fastbins
make: *** [Makefile.OpenCL:266: test] Aborted (core dumped)
```

* `make DEVICE=CPU NRUN=1 test`

```
[...]
./bin/autodock_cpu_16wi \
-ffile ./input/3ce3/derived/3ce3_protein.maps.fld \
-lfile ./input/3ce3/derived/3ce3_ligand.pdbqt \
-nrun 1 \
-ngen 27000 \
-psize 150 \
-resnam test \
-gfpop 0 \
-lsmet sw
AutoDock-GPU version: v1.3-2-g396556a773c2a1c153232228f35baaeedddb2dbb

Kernel source used for development:      ./device/calcenergy.cl                  
Kernel string used for building:         ./host/inc/stringify.h                  
Kernel compilation flags:                 -I ./device -I ./common -DN16WI   -cl-mad-enable
OpenCL device:                                  Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz
(Thread 0 is setting up Job 0)

Running Job #0:
Local-search chosen method is: Solis-Wets (sw)

Executing docking runs:
        20%        40%       60%       80%       100%
---------+---------+---------+---------+---------+
**************************************************

Job #0 took 32.167 sec after waiting 2.841 sec for setup

(Thread 0 is processing Job 0)
*** Error in `./bin/autodock_cpu_16wi': double free or corruption (fasttop): 0x0000000002e70ab0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777f5)[0x7fa7151607f5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8038a)[0x7fa71516938a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7fa71516d58c]
./bin/autodock_cpu_16wi[0x403e26]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7fa715109840]
./bin/autodock_cpu_16wi[0x404339]
======= Memory map: ========
00400000-00464000 r-xp 00000000 08:08 7080461                            /home/lvs/Desktop/AutoDock-GPU/bin/autodock_cpu_16wi
[...]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Makefile.OpenCL:266: recipe for target 'test' failed
make: *** [test] Aborted (core dumped)
```

The `develop` branch works without problems on both platforms. Can you please check this ?

**Comment by atillack** [comment]
@L30nardoSV Thank you. I'll look into it - of course the usual `make DEVICE=GPU test` was working fine for me. Thanks to your output it's very clear where it failed though ;-)

**Comment by atillack** [comment]
@L30nardoSV Could you test it with a filelist in the meantime? It'll likely still fail at the end but if it runs through to the end (as it should and did for me) that'll be a valuable data point :-)

**Comment by L30nardoSV** [comment]
@atillack Sure. Using this batch file:

```
cat batch.txt
AD-GPU_set_of_42/data/1ac8/protein.maps.fld
AD-GPU_set_of_42/data/1ac8/rand-0.pdbqt
Ligand0
AD-GPU_set_of_42/data/1ac8/rand-1.pdbqt
Ligand1
AD-GPU_set_of_42/data/1ac8/rand-2.pdbqt
Ligand2
```
and this command: `./bin/autodock_gpu_64wi -nrun 100 -ngen 27000 -psize 150 -gfpop 0 -lsmet sw -filelist batch.txt`

The output:

```bash
Running 3 jobs in pipeline mode
AutoDock-GPU version: v1.3-2-g396556a773c2a1c153232228f35baaeedddb2dbb

Kernel source used for development:      ./device/calcenergy.cl                  
Kernel string used for building:         ./host/inc/stringify.h                  
Kernel compilation flags:                 -I ./device -I ./common -DN64WI   -cl-mad-enable
OpenCL device:                           GeForce RTX 2070 SUPER
(Thread 0 is setting up Job 0)

Running Job #0:
   Fields from: AD-GPU_set_of_42/data/1ac8/protein.maps.fld
   Ligands from: AD-GPU_set_of_42/data/1ac8/rand-0.pdbqt
Local-search chosen method is: Solis-Wets (sw)

Executing docking runs:
        20%        40%       60%       80%       100%
---------+---------+---------+---------+---------+
**************************************************

Job #0 took 1.783 sec after waiting 0.444 sec for setup

(Thread 0 is processing Job 0)
(Thread 0 is setting up Job 1)

Running Job #1:
   Fields from: AD-GPU_set_of_42/data/1ac8/protein.maps.fld
   Ligands from: AD-GPU_set_of_42/data/1ac8/rand-1.pdbqt
Local-search chosen method is: Solis-Wets (sw)

Executing docking runs:
        20%        40%       60%       80%       100%
---------+---------+---------+---------+---------+
**************************************************

Job #1 took 1.771 sec after waiting 0.099 sec for setup

(Thread 0 is processing Job 1)
(Thread 0 is setting up Job 2)

Running Job #2:
   Fields from: AD-GPU_set_of_42/data/1ac8/protein.maps.fld
   Ligands from: AD-GPU_set_of_42/data/1ac8/rand-2.pdbqt
Local-search chosen method is: Solis-Wets (sw)

Executing docking runs:
        20%        40%       60%       80%       100%
---------+---------+---------+---------+---------+
**************************************************

Job #2 took 1.772 sec after waiting 0.095 sec for setup

(Thread 0 is processing Job 2)
double free or corruption (!prev)
Aborted (core dumped)
```

**Comment by atillack** [comment]
@L30nardoSV Thanks :-)

**Review by L30nardoSV — APPROVED** [review]
@atillack. Thanks, looks good and works when using long paths.

**Review by diogomart — APPROVED** [review]
Looks good on my end, either with or without OVERLAP=ON, and `-lfile` or `-filelist` :-)

**Comment by atillack** [comment]
@L30nardoSV @diogomart @jeeberhardt Thanks for your comments (on and off GH). I will go ahead and merge :-)

**Pull request merged**
