### PR TITLE
Upstreaming of CUDA extensions

### PR DESCRIPTION
**Pull request by jefflarkin**
This PR includes a post of AutoDock to CUDA, which enables running on Summit and has demonstrated a performance benefit over the OpenCL version on machine where both CUDA and OpenCL are available. A variety of changes are included:

* Relicenses portions from GPL to LGPL
* Optimized CUDA version
* Introduces a filelist option to perform a series of experiments rather than each experiment individually
* Adds a pipelining option (`make DEVICE=GPU OVERLAP=ON`) when filelist is use to overlap CPU and GPU operations
* Pre-allocates GPU buffers to max size to reduce the overheads associated with GPU allocation and deallocation
* Pre-loads ligand files to reduce file i/o
* Fixes to REPRO option to make it more reliable. 

Below are results comparing the results running https://github.com/diogomart/AD-GPU_set_of_42 using this new code and comparing to the reference energies in ligand_properties.csv. The cells are the absolute difference for each run compared to the reference energy. First is running each individually.

|      |     0 |     1 |     2 |
|:-----|------:|------:|------:|
| 1kzk | -0.02 | -0.03 | -0.07 |
| 1hnn | -0.18 | -0.18 | -0.17 |
| 1m2z | -0.08 | -0.07 | -0.08 |
| 1of6 | -0.17 | -0.05 | -0.1  |
| 1mzc | -0.02 | -0.02 | -0.02 |
| 1n46 | -0.1  | -0.09 | -0.15 |
| 1nav | -0.23 | -0.39 | -0.48 |
| 1lpz | -0.4  | -0.13 | -0.12 |
| 1k3u | -1.56 | -0.22 | -0.5  |
| 1jla | -0.21 | -0.1  | -0.1  |
| 1p62 | -0.06 | -0.12 | -0.06 |
| 1hwi | -0.04 | -0.04 | -0.12 |
| 1jje | -0.93 | -0.24 | -0.22 |
| 1ac8 | -0.02 | -0.01 | -0.01 |
| 1owe | -0.19 | -0.44 | -0.53 |
| 1p2y | -0.09 | -0.08 | -0.1  |
| 2brt | -0.13 | -0.32 | -0.13 |
| 1ywr | -0.12 | -0.33 | -0.15 |
| 1pmn | -0.31 | -0.31 | -0.36 |
| 1r55 | -0.04 | -0.03 | -0.02 |
| 1t40 | -0.84 | -0.43 | -0.28 |
| 1ig3 | -0.21 | -0.24 | -0.21 |
| 1y6b | -0.03 | -0.04 | -0.03 |
| 5wlo | -0.01 | -0.03 | -0.01 |
| 2wbg | -0.08 | -0.04 | -0.07 |
| 1lrh |  0.13 | -0.19 | -0.24 |
| 1yv3 | -0.07 | -0.06 | -0.08 |
| 1opk | -0.1  | -0.15 | -0.09 |
| 1v0p | -0.03 | -0.04 | -0.02 |
| 1l7f | -0.02 | -0.02 | -0.02 |
| 1gkc | -0.09 | -0.07 | -0.13 |
| 1sq5 | -0.04 | -0.02 | -0.01 |
| 1t46 | -0.14 | -0.28 | -0.24 |
| 1yqy | -0.4  | -0.35 | -0.24 |
| 2bsm | -0.15 | -0.18 | -0.15 |
| 2bm2 | -0.81 | -0.06 | -0.76 |
Mean Error: -0.178

This is running all of the same experiments in a single filelist and using pipelining with 2 OpenMP threads. 

|      |     0 |     1 |     2 |
|:-----|------:|------:|------:|
| 1owe | -0.27 | -0.26 | -0.16 |
| 1mzc | -0.05 | -0.02 | -0.02 |
| 1yqy | -0.48 | -0.27 | -0.34 |
| 1k3u | -0.17 | -1.51 | -0.12 |
| 5wlo | -0.02 | -0.01 | -0.02 |
| 1yv3 | -0.04 | -0.07 | -0.11 |
| 1hwi | -0.03 | -0.06 | -0.04 |
| 2brt | -0.15 | -0.12 | -0.26 |
| 1ac8 | -0.01 | -0.02 | -0.02 |
| 1hnn | -0.18 | -0.18 | -0.13 |
| 1jla | -0.08 | -0.24 | -0.14 |
| 1p62 | -0.07 | -0.08 | -0.13 |
| 1jje | -0.41 | -0.09 | -0.15 |
| 1nav | -0.41 | -0.41 | -0.23 |
| 1t46 | -0.22 | -0.22 | -0.15 |
| 1r55 | -0.03 | -0.03 | -0.02 |
| 1t40 | -1.22 | -0.5  | -0.19 |
| 1n46 | -0.13 | -0.14 | -0.12 |
| 1sq5 | -0.01 | -0.06 | -0.11 |
| 1gkc | -0.09 | -0.3  | -0.11 |
| 1ig3 | -0.22 | -0.14 | -0.11 |
| 1lpz | -0.33 | -0.25 | -0.11 |
| 1v0p | -0.09 | -0.02 | -0.02 |
| 1l7f | -0.02 | -0.02 | -0.02 |
| 1pmn | -0.18 | -0.31 | -0.19 |
| 1opk | -0.14 | -0.14 | -0.18 |
| 1ywr | -0.19 | -0.22 | -0.14 |
| 1kzk | -0.02 | -0.02 | -0.02 |
| 1of6 | -0.12 | -0.16 | -0.09 |
| 1p2y | -0.07 | -0.06 | -0.09 |
| 2bm2 | -0.55 | -0.37 | -0.95 |
| 2wbg | -0.04 | -0.08 | -0.02 |
| 1y6b | -0.05 | -0.03 | -0.04 |
| 1m2z | -0.1  | -0.07 | -0.05 |
| 1lrh | -0.02 |  0.01 | -0.17 |
| 2bsm | -0.16 | -0.21 | -0.12 |
Mean Error: -0.166

### CODE REVIEW

**Comment by atillack** [comment]
Hi Jeff, thank you very much. I look forward working on getting things merged.

**Comment by atillack** [comment]
@jefflarkin Cuda compilation works, but only on the second "make DEVICE=..." - I think it's the kernels.o that get's compiled before ...

**Comment by atillack** [comment]
@jefflarkin Both targets now compile on our machine. `make DEVICE=GPU NUMWI=128` automatically selects Cuda, `make DEVICE=OCLGPU NUMWI=128` can be used to overwrite this and both compile successfully.

**Comment by atillack** [comment]
Finally got to test the batch pipeline (I had issues compiling OpenMP before on our older Cuda machines) and used the opportunity to fix missing line breaks and such ...

**Comment by atillack** [comment]
@jefflarkin @L30nardoSV @diogomart From my perspective the code integration is almost done. There are a couple of minor loose ends - like `-asfreq` not doing anything on the Cuda side but they should be easy to tie up.

The major task now is testing, testing, testing ... It does feel like convergence is a bit slower. I suspect the "new" random number generator in miscellaneous.h/cpp (it probably won't be changed in this PR). So testing will be really helpful ...

**Comment by atillack** [comment]
One more thing: `-maxnev` is gone, instead `-nev` (as intended) serves it's purpose, with `-heuristics` it will cut it off in case the number of evals suggested by the heuristics is larger. The parameter `-heurmax` (from the current develop branch) controls the absolute asymptotic maximum of the heuristics (the default of 50 M should be good for most scenarios).

**Comment by jefflarkin** [comment]
Thanks @atillack . I'm doing a sweep of runs on my workstation now to confirm the answers and performance seem inline with what we'd been seeing.

**Comment by atillack** [comment]
@jefflarkin @L30nardoSV @diogomart This, at least from my end, should be it :-) Please test religiously and let me know if there are any show stoppers. One thing to note, with feature parity and everything using the exact (as possible) same algorithm while there still are speed variations it's not clear-cut anymore (for example `make DEVICE=GPU test` OpenCL is faster by 2x, while for 10gs with ADADELTA Cuda is faster by about 2x on our Titan V).

**Comment by atillack** [comment]
@jefflarkin The last fixes should now finally bring both codes to the same state ... Both are also now running at about the same speed for 10GS using ADADELTA on our Titan V. Finally taking out the restoring gradient that Scott's code still had from the time we had it on is responsible for that. You might think the 2x speedup using it is worth it (we thought so initially too) but with it in some cases converge 4x slower (require 4x more evals to get to a similar RMSD) so overall you'll loose time to solution ...

**Comment by diogomart** [comment]
13bb243eebd0a712a326320b0efb4bf0eeb80712 passed convergence tests for ADADELTA. Tested NUMWI=128, both OpenCL and CUDA. Convergence tests report the number of evals needed to find the (probable) global minimum. Going to test Solis-Wets next.

**Comment by diogomart** [comment]
Convergence tests for Solis-Wets also OK, both OpenCL and CUDA.

**Review by diogomart — APPROVED** [review]
Commit 13bb243eebd0a712a326320b0efb4bf0eeb80712 passed convergence tests (E_50) using either SWAT-3 or ADADELTA (with or without ADADELTA_AUTOSTOP), compiled with NUMWI=128, both OpenCL and CUDA.

**Comment by atillack** [comment]
@diogomart Thank you! I agree with you and after polishing things up (make sure all the license info is correct, etc.) over the weekend I think we should be ready to merge.

@L30nardoSV Please provide your feedback as soon as possible :-)

**Comment by L30nardoSV** [comment]
Hi all, 

@atillack: I have performed a simple experiment on a V100 GPU using commit 536f04b049e4ca1f0b347e98fad6c4bb559affae, but there is an error using `NUMWI=1` with the Cuda version. Some details:
* Using other NUMWI for Cuda produce _no_ error.
* All NUMWI values for OpenCL run fine.

Command: `$ make DEVICE=GPU NUMWI=1 test`:

```
./bin/autodock_gpu_1wi \
-ffile ./input/3ce3/derived/3ce3_protein.maps.fld \
-lfile ./input/3ce3/derived/3ce3_ligand.pdbqt \
-nrun 100 \
-ngen 27000 \
-psize 150 \
-resnam test \
-gfpop 0 \
-lsmet sw
AutoDock-GPU version: sd-tsri-291-g536f04b049e4ca1f0b347e98fad6c4bb559affae

CUDA Setup time 0.172691s
(Thread 0 is setting up Job 0)

Running Job #0:
Local-search chosen method is: Solis-Wets (sw)

Rest of Setup time 0.028219s

Executing docking runs:
        20%        40%       60%       80%       100%
---------+---------+---------+---------+---------+
gpu_gen_and_eval_newpops_kernel an illegal memory access was encountered
autodock_gpu_1wi: ./cuda/kernel4.cu:320: void gpu_gen_and_eval_newpops(uint32_t, uint32_t, float*, float*, float*, float*): Assertion `0' failed.
Makefile.Cuda:224: recipe for target 'test' failed
make: *** [test] Aborted (core dumped)
```

Can you reproduce this on your end?

**Comment by L30nardoSV** [comment]
**Update**: using the Cuda version with `NUMWI=2` on a V100 GPU led to _**same error above**_. 

I don't see such a problem using OpenCL on GPU and CPU.

**Comment by atillack** [comment]
@L30nardoSV Thanks for pointing that out. Since your code originally only went down to NUMWI=16 and NUMWI>=4 works with Cuda (and is lower than what you'd want for performance anyway) I think we can safely fix this by taking out NUMWI<4 for Cuda. What do you think?

**Comment by atillack** [comment]
Actually, I would even suggest anything under NUMWI=16 should not be used on a GPU. The reason I added the lower NUMWI values was for testing on CPU (with OpenCL) as some CPU OpenCL implementations (like the one on macOS) require NUMWI=1 to work properly. This is not an issue with Cuda, however.

**Comment by atillack** [comment]
@jefflarkin @L30nardoSV One thing I do notice with Cuda at NUMWI=4,8 and 16 is that the results distribution (the clustering histogram) of the 3ce3 test (make DEVICE=GPU NUMWI=4,8, xor 16 test) is worse than OpenCL's at the same NUMWI settings (this is with Solis-Wets). For example, at NUMWI=8 here is OpenCL's clustering histogram (just the numbers to make it readable here):

   1 |    -11.57 |   4 |    -11.41 |  99 
   2 |    -10.59 |  37 |    -10.59 |   1 

Here is the output with Cuda (at NUMWI=8):

   1 |    -11.39 | 100 |    -10.19 |  51
   2 |    -10.15 |  69 |     -9.24 |  29
   3 |     -8.99 |  16 |     -8.08 |   8
   4 |     -8.96 |  61 |     -8.96 |   1
   5 |     -8.69 |  33 |     -7.98 |   3
   6 |     -8.68 |  82 |     -8.68 |   1
   7 |     -8.29 |  27 |     -8.18 |   3
   8 |     -7.75 |  77 |     -7.63 |   2
   9 |     -7.71 |  89 |     -7.16 |   2

From NUMWI=32 onward Cuda's clustering histogram data is the same compared to OpenCL's above.

@jefflarkin Is there anything in the Cuda version that requires at least NUMWI=32?

**Comment by atillack** [comment]
@jefflarkin ADADELTA on Cuda at NUMWI<32 even introduces spuriously high energies ... NUMWI>=32 works fine again ...

**Comment by atillack** [comment]
@jefflarkin Yep, found it: warpbits = 5 and in kernel4: int warpid = threadIdx.x >> cData.warpbits

**Comment by atillack** [comment]
I would recommend capping Cuda at NUMWI>=32 and move along. Thoughts?

**Comment by L30nardoSV** [comment]
@atillack I see the issue with warpbits in your https://github.com/ccsb-scripps/AutoDock-GPU/pull/82#issuecomment-643688510. Does it (the usage of warpbits) result in any performance advantage or more efficient memory usage? If so, then it would be fine for this PR to just cap the Cuda version as you've just suggested.

However, what worries me a bit is the spurious energies you mention when using `NUMWI` < 32. I haven't checked that but, I would expect slower execution but not such energies when e.g. `NUMWI` = 16. Maybe a `threadIdx` usage requires a further check?

**Comment by L30nardoSV** [comment]
Based on the PR description, I ran a simple test of the `REPRO` option (again on a V100 GPU). I see the energies are not reproduced on every LGA run when this option is enabled.

As reference I used the master branch (0b6a1482935b8386f30a7fd15e1f1c3029cb68b3) for running `make DEVICE=GPU REPRO=YES test` (this still uses OpenCL), the clustering histogram shows the energy value of +6.21e+08 is _reproduced_:
```
1 | +6.21e+08 |   1 | +6.21e+08 |   2 |##
2 | +6.21e+08 |   2 | +6.21e+08 |   3 |###
3 | +6.21e+08 |   3 | +6.21e+08 |   2 |##
...
```
But using commit 536f04b049e4ca1f0b347e98fad6c4bb559affae, for both OpenCL and Cuda, it produces unexpected energy values in the histograms:

* `make DEVICE=OCLGPU REPRO=YES test`

```
1 |   +428.23 |  16 |   +428.23 |   1 |#
2 |  +1250.01 |  93 |  +1250.01 |   1 |#
3 |  +1260.45 |  48 |  +1260.45 |   1 |#
4 |  +3681.71 |  73 |  +3681.71 |   1 |#
5 |  +8001.03 |  32 |  +8001.03 |   1 |#
6 | +13634.35 |  19 | +13634.35 |   1 |#
7 | +22983.69 |  90 | +22983.69 |   1 |#
8 | +25042.81 |  78 | +25042.81 |   1 |#
...
```

* ` make DEVICE=GPU REPRO=YES test`
```
1 |    -11.58 |  66 |    -11.40 |  99 |#############...##
2 |    -10.64 |  11 |    -10.64 |   1 |#
```

Can you please try to reproduce this on your end?

**Comment by L30nardoSV** [comment]
Furthermore, I've also performed the above `REPRO` experiment using the commit eed190fd08844f5a1336cf36e267d7be3d8a6b61 in the  **develop** branch, which still produces expected energy values, i.e., all LGA runs producing +6.21e+08.

**Comment by atillack** [comment]
@L30nardoSV Fixed for the moment. And before you point out that OpenCL and Cuda are (slightly) different - REPRO=YES fixes the random number seed and should lead to the same results for a given run on a given architecture and device. We may need to put a bit closer scrutiny on this in the future but at least for my tests right now this is good enough.

**Comment by atillack** [comment]
When I run `make DEVICE=GPU/OCLGPU REPRO=YES test` on both Cuda and OpenCL the resulting energies are now **reproducibly** identical in a series of six reruns.

**Comment by L30nardoSV** [comment]
@atillack Sure, no problem, the main program structure is maintained in both Cuda and OpenCL versions, and that is great despite the necessary code changes.

Yes, the `REPRO`  option was added with that purpose in mind (very helpul to me in early debugging). In fact, when REPRO is enabled, a (very) similar energy value should result _regardless_ of the architecture/device. E.g., https://github.com/ccsb-scripps/AutoDock-GPU/commit/eed190fd08844f5a1336cf36e267d7be3d8a6b61 on other vendor GPUs and CPUs still results in +6.21e+08 as indicated above.

Just checked the recent 7fcda83ee13a985b35f75d4603556e3bc7f6bd00 commit on V100 and Vega56 GPUs, but it looks like `REPRO` is simply bypassed (i.e. energies are not reproduced) ... can you please confirm?

**Comment by atillack** [comment]
What you did with REPRO before was to fix the random numbers at 1 and 0.55 in the kernels. That is gone. Hardcoding things like that is not a good way to debug the code as you will always end up in the same edge case but leave other code paths untraveled. As both the host and device side random number generators are state based they are reproducible with the same input which is what REPRO provides. You can test this by rerunning the same test on the same machine and find that you will get the same energies.

There are limits to this of course, numerical precision being one for example, but also order of operations and such. This is why cross-architecture reproducible is problematic and I'd argue only achievable in trivial cases which ultimately is not very useful for debugging.

As it currently stands, runs on the same architecture (opencl or cuda) are reproducible on the same device with the same input. What more do you want?

**Comment by atillack** [comment]
I did test on Titan V with Cuda and OpenCL as well as on Radeon VII with OpenCL and make test energies are reproducible in the same device and architecture when i run multiple times. Also, the energies between Cuda and OpenCL are similar, but not identical, yet individually the energies stay the same upon rerun.

**Comment by L30nardoSV** [comment]
I want to understand, based on the execution results, how the usage/implementation of `REPRO` has been changed in this PR from what I recall. 

The initial implementation of REPRO does not cover all paths, but served to test differences and discover errors happening from one LGA run to another LGA run, even when porting to completely different architectures supporting OpenCL (e.g., FPGAs), that is mainly the reason I would like to keep it as such. I understand that at this point, as the code is mature enough for GPUs/CPUs, this looks not useful, but I think it may serve in future development (specially for upcoming  accelerators).

Perhaps the usage of `REPRO` is what we disagree. When introduced, it was meant to remove all randomness in order to reproduce virtually the **same** energies for every LGA run (despite the numerical precision as AFAIK we are always using FP32, and  despite the underlying FP hardware differences that are likely (& hopefully) abstracted away by OpenCL/CUDA) ...

... while in this PR here it seems only the initial seeds (in the host) are set constant. This allows kernels start from the same point in the score landscape, but eventually leads to different paths as randomness is still active on kernels, which indeed leads to valid & very similar docking results, but what I am considering **not truly** reproducible. 

No problem giving a pass on this, as this is arguable, but I just want to make clear the differences being introduced here.

**Comment by atillack** [comment]
@L30nardoSV I would argue the current evolution is truly reproducible (within the confines of numerical precision of course) even according to your definition. The only difference is that we are now using the same sequence of random numbers rather than hardcoding them to 1 or 0.55f (the same is true host side with different numbers).

To cheekily use your own argument: just because your numbers end up in the wall (as evidenced by the large energies) and therefore the variation that will be present in them is not visible (0.01 vs 10^8) doesn't make them truly reproducible either ;-)

**Comment by atillack** [comment]
In short, as written earlier, we might want to apply more scrutiny to this eventually but for now the changes (i think) are slightly better for debugging as it allows you to go through a run with realistic numbers.

**Comment by atillack** [comment]
To convince yourself, please run make test multiple times and save the energies of each run. You will find that they match within the same device and architecture.

**Comment by atillack** [comment]
The reason they may differ from device to device is that we use fast math and native_ functions which may be implemented slightly different.

**Comment by L30nardoSV** [comment]
@atillack I would say that in the current state is not truly reproducible as there is no way to ensure the same sequence of numbers are generated in two different LGAs. The present randomness there drives into different paths eventually. I agree that from a program execution to another, overall energies are reproducible, but not from one LGA run to another LGA run within a **single** program execution. This is what I mean.

You got me there with the large energies :smile:. Removing randomnes is not enough for debugging, but I think it may be a  way of early detecting sympthoms, specially when using RNG in kernels differently.

I guess we could keep discussing this interestingly on and on :smile: (which I enjoy). But I agree, let us consider this REPRO thing a pass. We should check this further, but  later on.

**Comment by L30nardoSV** [comment]
Besides that, I have other minor comments I am collecting, but I would like to double check. I will send them tomorrow at latest.

**Comment by atillack** [comment]
@L30nardoSV Good 🤠 Please send your comments as soon as possible as there are more PRs waiting...

The RNGs are actually not the problem as they are binary reproducible even... It's easy to add what you consider truly reproducible (that each LGA run has the same energy) but it boils down to a choice. When testing, I prefer more, rather than less, entropy as I think this has the chance to catch bugs more quickly. Your version is just a simple rerun away ...

**Comment by atillack** [comment]
Think of it this way: in your world each lga does precisely the same, in mine each lga does precisly the same when rerun, but not compared to the others at the same time

**Comment by jefflarkin** [comment]
> I would recommend capping Cuda at NUMWI>=32 and move along. Thoughts?

These kernels weren't designed for sub-warp execution. Scott and I have talked about some optimizations that would make this safe, but they've not been applied yet. I think the safest thing is to limit NUMWI to 32 or greater. This is how we've been testing it. For OpenCL on the CPU it makes sense to support lower. For OpenCL on the GPU, I'm a bit surprised it works at all, but there may be some safety measure put into the OpenCL runtime that I don't know about.

**Comment by L30nardoSV** [comment]
@atillack 
Another correction would be on the message displayed when invoking not-supported LS methods.

It looks only `sw`, `ad`, `adam` are supported in Cuda, but the program allows invoking other experimental LS methods like the `sd` or `fire`. It should indicate the fallback LS method being used, or simply disable them.

**Comment by L30nardoSV** [comment]
> Think of it this way: in your world each lga does precisely the same, in mine each lga does precisly the same when rerun, but not compared to the others at the same time

Agree. I think both worlds can co-exist to serve the different purposes, I do not think they clash with each other. Let us continue the discussion in https://github.com/ccsb-scripps/AutoDock-GPU/issues/83.

**Review by L30nardoSV — APPROVED** [review]
@atillack I am done with my review, thanks for the corrections!

@jefflarkin nice work! thanks for PR!

**Pull request merged**
