### PR TITLE
Cuda optimizations and other loose ends

### PR DESCRIPTION
**Pull request by atillack**
This PR improves the performance of the Cuda path to finally be on par with the OpenCL version.

This was achieved by eliminating unnecessary synchronizations across blocks and by using static shared memory (enabled by the v1.5 optimizations) instead of dynamic shared memory.

Docking times comparison with local search method specified and otherwise default settings for rand-0 ligand of Diogo's 42 dataset on an Nvidia Titan V:

**Solis-Wets**
| NUMWI | OpenCL v1.5 | Cuda v1.5 | this PR |
|--------:|:-------------:|:---------:|:-------:|
|         64 |              143 s |       209 s |    143 s |
|        128 |              128 s |       226 s |   139 s |

**Adadelta**
| NUMWI | OpenCL v1.5 | Cuda v1.5 | this PR |
|--------:|:-------------:|:---------:|:-------:|
|         64 |              263 s |      295 s |    257 s |
|        128 |              221 s |      282 s |    233 s |

Please do a full set of test runs for both Solis-Wets and Adadelta.

### CODE REVIEW

**Comment by diogomart** [comment]
E50s are looking good for CUDA, ADADELTA, 128wi, using filelist and overlap=on, single-GPU.
09d6579-ocl-128wi-ad_vs_PR151-107fd7a-cuda-128wi-overlap

**Comment by atillack** [comment]
@diogomart Great! Thank you.

P.S. For the record before anyone wonders: Versions before v1.5 had a rare bug with the 4elm2 pdbqt leading to an offset in energies ... the "outlier" number is actually the correct one ;-)

**Comment by diogomart** [comment]
Solis-Wets also looking good using v1.5 as reference :+1:  

adgpu-1 5 0-cuda-128wi-overlap-sw_vs_PR151-107fd7a-cuda-128wi-overlap-sw

**Comment by atillack** [comment]
@diogomart Thank you. Fingers crossed for the last set of tests :-)

**Comment by diogomart** [comment]
Running on 8 GPUs simultaneously also works :) This is good to merge :+1: 
adgpu-1 5 0-cuda-128wi-overlap-sw_vs_PR151-f8fd68f-cuda-128wi-overlap-allgpu

**Review by diogomart — APPROVED** [review]

**Pull request merged**
