### PR TITLE
Make sure no doubles appear in single precision kernels

### PR DESCRIPTION
**Pull request by atillack**
There were a handful of 1.0 instead of 1.0f (as an example) cases of unintended doubles in the kernels. This PR fixes those.

I tested both Cuda and OpenCL codes on Linux and macOS. Please quickly test and if you can find more cases of "accidental" doubles please flag them ;-)

### CODE REVIEW

**Comment by L30nardoSV** [comment]
Please check the ones I found using `egrep -inr '[0-9]+[.][0-9]`:

OpenCL
* https://github.com/ccsb-scripps/AutoDock-GPU/blob/48219340660d0e2e6c355e1fe1fb1ab7b3b450ba/device/calcgradient.cl#L55
* https://github.com/ccsb-scripps/AutoDock-GPU/blob/48219340660d0e2e6c355e1fe1fb1ab7b3b450ba/device/kernel3.cl#L181

CUDA
* https://github.com/ccsb-scripps/AutoDock-GPU/blob/48219340660d0e2e6c355e1fe1fb1ab7b3b450ba/cuda/calcMergeEneGra.cu#L212

**Comment by atillack** [comment]
@L30nardoSV Thank you! Nice egrep mojo :-)

**Comment by atillack** [comment]
Also, technically the race is over now - the last commit netted Diogo 1041 additional x.x -> x.xf's :-D

**Review by diogomart — APPROVED** [review]
Looks good!

**Review by L30nardoSV — APPROVED** [review]
It looks good :)

**Comment by atillack** [comment]
Thank you, will merge :-)

**Pull request merged**
