### PR TITLE
Windows build and OpenCL/Cuda host code unification

### PR DESCRIPTION
**Pull request by atillack**
This PR adds functionality to build an OpenCL Windows version using VisualStudio. Additionally, to make future expansions a bit easier, I merged the OpenCL and Cuda host source (performdocking.h/cpp).

In order to do this the new windows/ directory contains OpenCL headers and link lib files with compatible licenses from Khronos - license files  are included.

This PR also bumps the base version up to v1.6 (Windows builds will be labeled already with it) for us to slowly gear up towards a new release ... 70+ commits do deserve a bump to v1.6 ;-)

Please test extensively. Although there should be no algorithmic changes the code reshuffling needs full tests for both Cuda and OpenCL to verify.

### CODE REVIEW

**Review by rwxayheee — APPROVED** [review]
This update enabled writing nonempty XML and DLG files. The contents are visually correct. Thank you for the great work!

**Comment by diogomart** [comment]
Both OpenCL and CUDA look good :+1:

79f13c7-ocl-128wi_vs_PR255-7007db8-cuda-128wi-overlap
79f13c7-ocl-128wi_vs_PR255-7007db8-ocl-128wi-overlap

**Comment by atillack** [comment]
@diogomart Great! Thank you :-)

**Review by diogomart — APPROVED** [review]
E50s look good :+1:

**Comment by atillack** [comment]
Thank you everyone!

**Pull request merged**
