### PR TITLE
Major feature updates and code optimizations

### PR DESCRIPTION
**Pull request by atillack**
This PR contains major feature updates and code optimizations that will be v1.5 when it's finished:

- Multi-GPU support with automatic detection of devices (both Cuda and OpenCL). Requires compilation with `OVERLAP=ON` to parallelize running on multiple GPUs. During parallel execution, load balancing is achieved by each waiting thread grabbing the next available GPU.
- Ability to use multiple ligand pdbqt files with the `--filelist` argument (as an alternative to the file list file) to dock all ligands with the specified grid maps, flex res, and other settings
- Major speedups for both setup and processing (each about 2-3x)
- Grid maps are now read precisely once for any number of fld files in a file list and there is no more limit to their number. This was achieved by unifying the grid map code and moving every grid related memory back into the grid data structure.
- Rewrite of the pdbqt (ligand and flex res) and grid map read-in code to optimize file IO. Now, each pdbqt is only read once and not four times - so this should help in IO-limited situations ...
- Implemented full fld file parsing for the respective atom types and their associated map files.
- Added `adgpu_analysis` tool that can also be compiled when no `DEVICE` (and hence no Cuda or OpenCL) is specified during compilation to have `--xml2dlg` functionality without needing an accelerator framework.
- Reference ligand energy output (of either input ligand pose or reference ligand) with `--rlige 1` has been extended to full dlg-style energy output and is also added to reference ligand output in dlg output.
- Contact analysis output now is also added to reference (`--xraylfile`) as well input ligand output in dlg when specified
- Added ability to specify reference (xray) ligand in filelist format: lines ending in `.pdbqt*` are now interpreted as the reference ligand for successively specified ligands

I did test using the usual `make test` test case, converted multiple xml files, and reproduced values with multiple flex res. Please test and make sure ligands and flex res pdbqt are still read correctly on your end.

### CODE REVIEW

**Review by diogomart — APPROVED** [review]
Tested --xml2dlg and --contact_analysis with a couple ligands. Both rehydration and contact analysis match the output of v1.4 exactly. This was on Linux, work groups with 128wi, and OpenCL. Good to go :-)

**Review by jeeberhardt — APPROVED** [review]

**Comment by diogomart** [comment]
E50s are looking good for a51c8a3. Specs: OpenCL, num_wi=128, filelist (batches of 4 ligands), adadelta.
The outlier 4elm2 occurs because a bug has been fixed, but the reference data hasn't been updated yet.
09d6579-ocl-128wi-ad_vs_PR139-a51c8a3-ocl-128wi-overlap

**Comment by atillack** [comment]
@diogomart Thank you!

**Review by diogomart — APPROVED** [review]
Didn't test all the features to "maximum thoroughness" but everything I looked at worked fine :)

**Comment by atillack** [comment]
@diogomart Thanks! Merging now ...

**Pull request merged**
